baseURL="http://www.heyuan110.com"
languageCode="zh-hans"
defaultContentLanguage="en"
title="Bruce'sBlog"
theme="hermit"
#enableGitInfo=true
pygmentsCodefences=true
pygmentsUseClasses=true
#hasCJKLanguage=true#IfChinese/Japanese/Koreanisyourmaincontentlanguage,enablethistomakewordCountworksright.
rssLimit=10#MaximumnumberofitemsintheRSSfeed.
copyright="ThisworkislicensedunderaCreativeCommonsAttribution-NonCommercial4.0InternationalLicense."#ThismessageisonlyusedbytheRSStemplate.
enableEmoji=true#Shorthandemojisincontentfiles-https://gohugo.io/functions/emojify/
#googleAnalytics="UA-166045776-1"
#disqusShortname="yourdiscussshortname"

[author]
name="Bruce'sBlog"

[blackfriday]
#hrefTargetBlank=true
#noreferrerLinks=true
#nofollowLinks=true

[taxonomies]
tag="tags"
#Categoriesaredisabledbydefault.

[params]
since="2015"
toc=true

dateform="Jan2,2006"
dateformShort="Jan2"
dateformNum="2006-01-02"
dateformNumTime="2006-01-0215:04-0700"

#Metadatamostlyusedindocument'shead
description="bruce,hebruce110,laravel,java,springweb,vue,ios,博客,go,golang,源码分析,系列教程"
#images=[""]
themeColor="#494f5c"

homeSubtitle="常笑笑自己!"
footerCopyright='&#183;版权所有'
#bgImg=""#Homepagebackground-imageURL

#Prefixoflinktothegitcommitdetailpage.GitInfomustbeenabled.
gitUrl="https://github.com/heyuan110/heyuan110.github.com/commit/"

#TogglingthisoptionneedstorebuildSCSS,requiresHugoextendedversion
justifyContent=false#Set"text-align:justify"to`.content`.

relatedPosts=false#Addarelatedcontentsectiontoallsinglepostspage

code_copy_button=true#Turnon/offthecode-copy-buttonforcode-fields

#Addcustomcss
#customCSS=["css/foo.css","css/bar.css"]

#SocialIcons
#Checkhttps://github.com/Track3/hermit#social-iconsformoreinfo.

[[params.social]]
name="github"
url="https://github.com/hebruce110"

[menu]

[[menu.main]]
name="文章"
url="posts/"
weight=10

[[menu.main]]
name="标签"
url="tags/"
weight=10

[[menu.main]]
name="关于"
url="about/"
weight=20

[[menu.nav]]
name="文章"
url="posts/"
weight=10

[[menu.nav]]
name="AI系列"
url="ai-categories/"
weight=11

[[menu.nav]]
name="Java系列"
url="java-categories/"
weight=12

[[menu.nav]]
name="Go系列"
url="go-categories/"
weight=13

[[menu.nav]]
name="Docker系列"
url="docker-categories/"
weight=14

[[menu.nav]]
name="Linux系列"
url="linux-categories/"
weight=15



